logging:
  level:
    org.woodwhales.ncov: debug

spring:
  application: 
    name: 2019-nCoV
  thymeleaf:
    cache: false
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/2019-ncov?serverTimezone=Asia/Shanghai&useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root